version: '3.4'

services:
  db:
    image: postgres:16.10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
    mem_limit: 6g
    cpus: 6
    networks:
      net6:
        ipv4_address: 172.28.10.3

  odoo17:
    image: odoo:19.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10019:8069"
      - "20014:8072"
    tty: true
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      - ./etc:/etc/odoo
    restart: always
    mem_limit: 6g
    cpus: 6
    networks:
      net6:
        ipv4_address: 172.28.10.2

networks:
  net6:
    name: odoo-net6
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/29
          gateway: 172.28.10.1
